/* 
 * Copyright 2015 Cognitive Medical Systems, Inc (http://www.cognitivemedicine.com).
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.cognitive.nsf.management.ui;

import com.cognitive.nsf.management.fact.control.NoAlternativeModelFound;
import com.cognitive.nsf.management.model.ARDSModel;
import com.cognitive.nsf.management.model.AsthmaModel;
import com.cognitive.nsf.management.model.PneumoniaModel;

/**
 *
 * @author esteban
 */
public class NoPerformantModelFoundPanel extends javax.swing.JPanel {

    private final NoAlternativeModelFound noAlternativeModelFound;
    private final ManagementConsole parent;

    public NoPerformantModelFoundPanel(ManagementConsole parent, NoAlternativeModelFound noAlternativeModelFound) {
        this.parent = parent;
        this.noAlternativeModelFound = noAlternativeModelFound;
        initComponents();
        
        this.lblDiagnosis.setText(this.parent.getSelectedDiagnosisName());
        
        this.lblResultHigh.setText(this.noAlternativeModelFound.getModelWeights().get(ARDSModel.NAME)+"");
        this.lblResultModerate.setText(this.noAlternativeModelFound.getModelWeights().get(PneumoniaModel.NAME)+"");
        this.lblResultLow.setText(this.noAlternativeModelFound.getModelWeights().get(AsthmaModel.NAME)+"");
        
        this.lblThreshold.setText(parent.getThreshold());
        
    }
    
    public boolean isContinueWithVentilatorModelSelected(){
        return this.chkNewVentilatorModel.isSelected();
    }
    
    public String getSelectedVentilatorModel(){
        return this.cboVentilatorModel.getSelectedItem().toString();
    }
    
    public boolean isContinueWithNewDiagnosisSelected(){
        return this.chkNewDiagnosis.isSelected();
    }
    
    public String getSelectedDiagnosis(){
        return this.cboDiagnosis.getSelectedItem().toString();
    }
    
    public boolean isDoNothingSelected(){
        return this.chkDoNothing.isSelected();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDiagnosis = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResultModerate = new javax.swing.JLabel();
        lblResultLow = new javax.swing.JLabel();
        lblResultHigh = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        chkNewVentilatorModel = new javax.swing.JRadioButton();
        chkNewDiagnosis = new javax.swing.JRadioButton();
        chkDoNothing = new javax.swing.JRadioButton();
        cboVentilatorModel = new javax.swing.JComboBox();
        cboDiagnosis = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lblThreshold = new javax.swing.JLabel();

        lblTitle.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        lblTitle.setText("No satisfactory model found!");

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText("Diagnosis:");

        lblDiagnosis.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel3.setText("Results:");

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel4.setText("High Volume:");

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel5.setText("Moderate Volume:");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel6.setText("Low Volume:");

        lblResultModerate.setText("jLabel2");

        lblResultLow.setText("jLabel2");

        lblResultHigh.setText("jLabel2");

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel10.setText("What's next?");

        buttonGroup1.add(chkNewVentilatorModel);
        chkNewVentilatorModel.setText("Continue with this Ventilator model:");

        buttonGroup1.add(chkNewDiagnosis);
        chkNewDiagnosis.setText("Start over using this new diagnosis:");
        chkNewDiagnosis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNewDiagnosisActionPerformed(evt);
            }
        });

        buttonGroup1.add(chkDoNothing);
        chkDoNothing.setSelected(true);
        chkDoNothing.setText("Do nothing");
        chkDoNothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDoNothingActionPerformed(evt);
            }
        });

        cboVentilatorModel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "High", "Moderate", "Low" }));

        cboDiagnosis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ARDS", "Pneumonia", "Asthma" }));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText("Threshold:");

        lblThreshold.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(43, 43, 43)
                                .addComponent(lblResultHigh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultModerate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(48, 48, 48)
                                .addComponent(lblResultLow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(lblThreshold, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(lblDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkDoNothing)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkNewDiagnosis)
                                            .addComponent(chkNewVentilatorModel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cboDiagnosis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cboVentilatorModel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addContainerGap(52, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDiagnosis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblThreshold))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblResultHigh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblResultModerate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblResultLow))
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNewVentilatorModel)
                    .addComponent(cboVentilatorModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkNewDiagnosis)
                    .addComponent(cboDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkDoNothing)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkNewDiagnosisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNewDiagnosisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkNewDiagnosisActionPerformed

    private void chkDoNothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDoNothingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDoNothingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cboDiagnosis;
    private javax.swing.JComboBox cboVentilatorModel;
    private javax.swing.JRadioButton chkDoNothing;
    private javax.swing.JRadioButton chkNewDiagnosis;
    private javax.swing.JRadioButton chkNewVentilatorModel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblResultHigh;
    private javax.swing.JLabel lblResultLow;
    private javax.swing.JLabel lblResultModerate;
    private javax.swing.JLabel lblThreshold;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
